### ISSUE TITLE
Multiple Zones with Same name / Public vs. Private for Split DNS

### ISSUE THREAD

**Issue by tmthbrunner** [troydieter/r53_backups_cdk#1]
Great solution... works fantastic. Just wanted to make you aware it does not differentiate between public and private zones.
In a split DNS scenario, you could have public and private zones with the same name. It only writes one of them to the s3 bucket currently.

**Comment by troydieter** [comment]
Thanks for this @tmthbrunner ! That is an accurate point, and one we should rectify. Marking this as a bug and will work to get a change in.

**Comment by troydieter** [comment]
Hi @tmthbrunner - again, thanks for the very valuable feedback. I've [rectified this](389d2468fdab8c7c1806e7a7d76ddb0a469eaf0c) and pushed a change that now appends `_public` or `_private` depending on the Route53 Hosted Zone type. 

Tested and working as expected, feel free to re-open any issues pertaining to this if you see otherwise.
